### ISSUE TITLE
DateIssue

### ISSUE THREAD

**Issue by mathiassteger** [ixno/TeX#1]
I recently used your design for one of my tasks in university. I thought it was great (5/7). My tutor hated it though, as it does not provide the current date. He said: 

> "This is the worst design in the history of designs, maybe ever."

I will not use this design until this issue is fixed.

**Comment by hwiards** [comment]
Hi, this issue is fixed in https://github.com/hwiards/TeX/commit/7b9885bf8b042d1b6f1c16fec24c93989a959a0d
